version: '3.8'

services:
  api:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/lightpost
    volumes:
      - ./:/app:delegated
      - app_node_modules:/app/node_modules
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lightpost
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  app_node_modules: 